language: en
numSuggestions: 4
useGitignore: true
words:
  - Adguard
  - aflorzy
  - andrewflorzy
  - andrewtflores
  - astro
  - Bazarr
  - Caddyfile
  - containerd
  - daytrackr
  - distros
  - Dockerized
  - Dockge
  - Emby
  - fastcgi
  - fdba
  - Florzy
  - flotrade
  - FOSS
  - frontmatter
  - fullchain
  - Gitea
  - homelab
  - homelabbers
  - homelabbing
  - Homelabs
  - Immich
  - ispn
  - Jellyfin
  - Klipper
  - Kuma
  - letsencrypt
  - Macbook
  - newgrp
  - Nextcloud
  - NGRX
  - Notifiarr
  - Octo
  - Overallocate
  - Overseerr
  - partytown
  - privkey
  - Prowlarr
  - Radarr
  - Requestrr
  - scoobydoo
  - shoutout
  - SLES
  - Sonarr
  - Tailscale
  - Traefik
  - Truenas
  - Unraid
  - usermod
ignoreRegExpList:
  - /```[\s\S]*?```/
files:
  - "**/*.{md,mdx}"
enableFiletypes:
  - mdx
